package com.wavjaby.youtube.decrypt;

public enum ErrorType {
    CANT_GET_VIDEO_ID,
    CANT_GET_VIDEO_INFO,
    CANT_FIND_BASE_JS_URL,
    CANT_FIND_VIDEO_INFO,


    CANT_GET_BASE_JS,
    SIGNATURE_ENTRY_FUNCTION_NOT_FOUND,
    SIGNATURE_DECIPHER_FUNCTION_NOT_FOUND,
    UNKNOWN_SIGNATURE_TYPE,
}
